version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "javaPo1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6xljyzxnsq1y"
s3_prefix = "javaPo1"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=338422272978.dkr.ecr.ap-northeast-1.amazonaws.com/javapo1fe9ba5e1/helloworldfunction19d43fc4repo"]
